### ISSUE TITLE
pin PB10 is reserved for t5uid1

### ISSUE THREAD

**Issue by Big-Lope** [fryc88/klipper-sv06plus-screen#1]
I recently followed all installation steps and reflashed my firmware to the specifications listed on my SV06+. 

I have an error that states pin PB10 is reserved for t5uid1; I'm not sure if something else is using PB10 in my config however I know the issue is not firmware related. I have extensively checked my config and no pins are conflicting.

![image](https://github.com/fryc88/klipper-sv06plus-screen/assets/61567881/9a0dfa2a-1455-4b7e-8013-39259a9ac510)

![Screenshot 2023-05-11 124034](https://github.com/fryc88/klipper-sv06plus-screen/assets/61567881/2dedcdc2-c0d4-412a-a52f-ee77aee2ad3a)

**Comment by fryc88** [comment]
Please post your printer.cfg file and if you have any other cfg files included in it, post them as well.
That error should not occur.

**Comment by fryc88** [comment]
I'm closing it as no reply - more likely user error.
