### ISSUE TITLE
What is firmware5.bin ?

### ISSUE THREAD

**Issue by WayneManion** [fryc88/klipper-sv06plus-screen#2]
I didn't see a better place to ask this, so here goes. In the main branch of the repo there is a file called firmware5.bin. Is this a precompiled Klipper binary for the SV06 Plus?

Thanks

**Comment by fryc88** [comment]
Yes, it is, but for this specific branch that contains screen support.

**Comment by WayneManion** [comment]
Do you happen to know if there is a plan to integrate this branch with upstream Klipper at some point in the future?

**Comment by fryc88** [comment]
I'm not original author of it, and if i remember right Desuuu tried already and it didn't go any further, so i wouldn't expect that to happen ever.

**Comment by WayneManion** [comment]
Another dumb question: if I got a hold of the screen for a regular SV06 would it attach to the SV06 Plus controller board? Would it work with vanilla Klipper? I really don't care about the touch screen, I just want some kind of display for filament loading and stuff like that.

**Comment by fryc88** [comment]
Sorry, i've missed your question here somehow. Yes, you can use nearly any type of b&w screen with Klipper, it needs correct wiring of course.
Sovol board is based on Creality 4.2.7 with multiple changes, but most of pinout is matching it.
